import { useEffect, useMemo, useState } from 'react'
import { Download, Plus, Search, Trash2 } from 'lucide-react'
import { FieldGrid, Section, Tabs, Workspace } from '../components/WorkspaceUI'
import { patientService } from '../api/patientService'
import { scanService } from '../api/scanService'
import { workspaceService } from '../api/workspaceService'

const f=(key,label,type='text',options,addable=false)=>({key,label,type,options,addable})
const initial={from:'',to:'',sex:'',patientId:'',firstName:'',lastName:'',ageFrom:'',ageTo:'',ethnicOrigin:'',scanType:'',status:'',indication:'',diagnosis:'',referralDoctor:'',primaryConsultant:'',signedByLeft:'',signedByRight:'',typedBy:'',reviewedBy:'',icdCode:'',abnormal:false,ambiguity:false,growthAbnormality:false,normal:false,normalVariant:false}
const columnNames=['Patient ID','Name','Gender','Date of birth','Address','Visit date','Visit no','Referral doctor','Age','Alias ID','Scan type','Status','Diagnosis','Consultant']

export default function Analytics(){
 const [tab,setTab]=useState('Advanced query'),[patients,setPatients]=useState([]),[scans,setScans]=useState([]),[saved,setSaved]=useState([]),[query,setQuery]=useState(initial),[columns,setColumns]=useState(columnNames)
 useEffect(()=>{Promise.all([patientService.getPatients(),scanService.getScans(),workspaceService.list('saved-queries')]).then(([p,s,q])=>{setPatients(p.data||[]);setScans(s.data||[]);setSaved(q.data||[])})},[])
 const rows=useMemo(()=>scans.map((scan)=>{const patient=patients.find((p)=>[p.id,p.patient_id].includes(scan.patient_id));return{...scan,patient}}).filter((row)=>{
   const patient=row.patient||{},created=row.created_at?new Date(row.created_at):null,from=query.from?new Date(query.from):null,to=query.to?new Date(`${query.to}T23:59:59`):null,blob=JSON.stringify(row).toLowerCase()
   return(!from||created>=from)&&(!to||created<=to)&&(!query.patientId||String(patient.patient_id||'').toLowerCase().includes(query.patientId.toLowerCase()))&&(!query.firstName||String(patient.first_name||'').toLowerCase().includes(query.firstName.toLowerCase()))&&(!query.lastName||String(patient.last_name||'').toLowerCase().includes(query.lastName.toLowerCase()))&&(!query.sex||patient.gender===query.sex)&&(!query.ageFrom||Number(patient.age)>=Number(query.ageFrom))&&(!query.ageTo||Number(patient.age)<=Number(query.ageTo))&&(!query.ethnicOrigin||String(patient.ethnic_origin||'').toLowerCase().includes(query.ethnicOrigin.toLowerCase()))&&(!query.scanType||row.scan_type===query.scanType)&&(!query.status||String(row.status||'').toLowerCase().includes(query.status.toLowerCase()))&&(!query.indication||blob.includes(query.indication.toLowerCase()))&&(!query.diagnosis||blob.includes(query.diagnosis.toLowerCase()))&&(!query.referralDoctor||blob.includes(query.referralDoctor.toLowerCase()))&&(!query.primaryConsultant||blob.includes(query.primaryConsultant.toLowerCase()))&&(!query.signedByLeft||blob.includes(query.signedByLeft.toLowerCase()))&&(!query.signedByRight||blob.includes(query.signedByRight.toLowerCase()))&&(!query.typedBy||blob.includes(query.typedBy.toLowerCase()))&&(!query.reviewedBy||blob.includes(query.reviewedBy.toLowerCase()))&&(!query.icdCode||blob.includes(query.icdCode.toLowerCase()))&&(!query.abnormal||row.abnormal)&&(!query.ambiguity||row.ambiguity)&&(!query.growthAbnormality||row.growthAbnormality)&&(!query.normal||row.normal)&&(!query.normalVariant||row.normalVariant)
 }),[patients,scans,query])
 const stats=useMemo(()=>['Adult Echo','Pediatric Echo','Fetal Echo'].map((type)=>({type,count:rows.filter((row)=>row.scan_type===type).length,completed:rows.filter((row)=>row.scan_type===type&&String(row.status).toLowerCase()==='completed').length})),[rows])
 const exportCsv=()=>{const headers=columns;const values=(row)=>columns.map((column)=>{const p=row.patient||{};const map={'Patient ID':p.patient_id,'Name':`${p.first_name||''} ${p.last_name||''}`.trim(),'Gender':p.gender,'Date of birth':p.dob,'Address':[p.street,p.area,p.district_city].filter(Boolean).join(' '),'Visit date':row.visit_date||row.created_at,'Visit no':row.visit_id,'Referral doctor':row.referral_doctor,'Age':p.age,'Alias ID':p.alias_id,'Scan type':row.scan_type,'Status':row.status,'Diagnosis':row.diagnosis||row.impression,'Consultant':row.primaryConsultant};return `"${String(map[column]||'').replaceAll('"','""')}"`}).join(',');const content=[headers.join(','),...rows.map(values)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/csv'}));a.download='echo-query.csv';a.click()}
 return <Workspace title="Queries & analytics" description="Advanced clinical queries, reusable search definitions, printable columns and scan statistics." actions={<button className="secondary-button" onClick={exportCsv}><Download className="h-4 w-4"/>Export selected columns</button>}><Tabs items={['Advanced query','Saved queries','Statistics']} value={tab} onChange={setTab}/>
 {tab==='Advanced query'&&<><Section title="Sonocare query criteria"><FieldGrid fields={[f('from','From date','date'),f('to','To date','date'),f('sex','Sex','select',['Male','Female','Unknown']),f('patientId','Patient ID'),f('firstName','First name'),f('lastName','Last name'),f('ageFrom','Age from','number'),f('ageTo','Age to','number'),f('ethnicOrigin','Ethnic origin','select',[],true),f('scanType','Scan type','select',['Adult Echo','Pediatric Echo','Fetal Echo','Template report']),f('status','Investigation status','select',['Draft','In progress','Completed']),f('indication','Indication'),f('diagnosis','Diagnosis / final impression'),f('referralDoctor','Referral doctor'),f('primaryConsultant','Primary consultant'),f('signedByLeft','Signed by (L)'),f('signedByRight','Signed by (R)'),f('typedBy','Typed by'),f('reviewedBy','Reviewed by'),f('icdCode','Provisional / final ICD code')]} data={query} setData={setQuery}/><div className="mt-4 grid gap-2 sm:grid-cols-5">{[['abnormal','Abnormal'],['ambiguity','Ambiguity'],['growthAbnormality','Growth abnormality'],['normal','Normal'],['normalVariant','Normal variant']].map(([key,label])=><label key={key} className="flex gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={query[key]} onChange={(e)=>setQuery({...query,[key]:e.target.checked})}/>{label}</label>)}</div><div className="mt-4 flex gap-2"><button className="primary-button"><Search className="h-4 w-4"/>Search</button><button className="secondary-button" onClick={()=>setQuery(initial)}>Clear</button></div></Section><Section title="Select columns to print" className="mt-4"><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-5">{columnNames.map((column)=><label key={column} className="flex gap-2 text-sm"><input type="checkbox" checked={columns.includes(column)} onChange={()=>setColumns(columns.includes(column)?columns.filter((item)=>item!==column):[...columns,column])}/>{column}</label>)}</div></Section><Results rows={rows}/></>}
 {tab==='Saved queries'&&<SavedQueries saved={saved} setSaved={setSaved} query={query} setQuery={setQuery} setTab={setTab}/>}
 {tab==='Statistics'&&<><Section title="Statistics filters"><FieldGrid fields={[f('from','From date','date'),f('to','To date','date'),f('sex','Sex','select',['Male','Female','Unknown']),f('icdCode','Provisional / final ICD code')]} data={query} setData={setQuery}/></Section><div className="mt-4 grid gap-4 lg:grid-cols-3">{stats.map((item)=><div key={item.type} className="rounded-xl border bg-white p-6 shadow-sm"><p className="text-sm font-medium text-slate-500">{item.type}</p><p className="mt-2 text-4xl font-semibold">{item.count}</p><p className="mt-2 text-sm text-emerald-700">{item.completed} completed</p></div>)}</div></>}
 </Workspace>
}

function Results({rows}){return <Section title={`Query results (${rows.length})`} className="mt-4"><div className="overflow-auto"><table className="data-table min-w-[900px]"><thead><tr><th>Patient</th><th>Scan type</th><th>Status</th><th>Indicator</th><th>Diagnosis</th><th>Created</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.id||index}><td>{row.patient?.patient_id||'—'}<div className="text-xs text-slate-500">{row.patient?.first_name} {row.patient?.last_name}</div></td><td>{row.scan_type}</td><td>{row.status}</td><td>{row.abnormal?'Abnormal':row.ambiguity?'Ambiguity':row.growthAbnormality?'Growth abnormality':'—'}</td><td>{row.diagnosis||row.impression||'—'}</td><td>{row.created_at?new Date(row.created_at).toLocaleDateString():'—'}</td></tr>)}</tbody></table>{!rows.length&&<p className="py-10 text-center text-sm text-slate-500">No records match this query.</p>}</div></Section>}

function SavedQueries({saved,setSaved,query,setQuery,setTab}){const [name,setName]=useState('');const add=async()=>{if(!name.trim())return;const result=await workspaceService.create('saved-queries',{name:name.trim(),query});setSaved([...saved,result.data]);setName('')};const remove=async(item)=>{await workspaceService.remove('saved-queries',item.id);setSaved(saved.filter((entry)=>entry.id!==item.id))};return <Section title="Saved queries"><div className="mb-4 flex gap-2"><input className="field-control max-w-sm" value={name} onChange={(e)=>setName(e.target.value)} placeholder="Save as query name"/><button className="primary-button" onClick={add}><Plus className="h-4 w-4"/>Save query</button></div><div className="space-y-2">{saved.map((item)=><div key={item.id} className="flex items-center rounded-lg border p-3"><button onClick={()=>{setQuery({...initial,...item.query});setTab('Advanced query')}} className="flex-1 text-left font-medium">{item.name}</button><button onClick={()=>remove(item)} className="rounded p-2 text-red-600"><Trash2 className="h-4 w-4"/></button></div>)}</div></Section>}
